-- ============================================================================
-- MIGRATION 011: PHASE 3.1 SALES FOUNDATION & QUOTATIONS
-- ============================================================================

CREATE TABLE IF NOT EXISTS sales_quotations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id VARCHAR(64) NOT NULL,
  company_id UUID NOT NULL REFERENCES companies(id),
  quotation_number VARCHAR(64) NOT NULL,
  revision_number INTEGER NOT NULL DEFAULT 1,
  customer_id UUID NOT NULL REFERENCES customers(id),
  quotation_date VARCHAR(10) NOT NULL,
  validity_date VARCHAR(10) NOT NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'INR',
  exchange_rate NUMERIC(18,6) NOT NULL DEFAULT 1.000000,
  sales_representative_id UUID REFERENCES users(id),
  pricing_list_id UUID REFERENCES pricing_lists(id),
  billing_address_id UUID NOT NULL REFERENCES commercial_addresses(id),
  shipping_address_id UUID NOT NULL REFERENCES commercial_addresses(id),
  billing_address_snapshot JSONB NOT NULL,
  shipping_address_snapshot JSONB NOT NULL,
  contact_id UUID REFERENCES commercial_contacts(id),
  contact_snapshot JSONB,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  notes TEXT,
  terms_and_conditions TEXT,
  subtotal_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  header_discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  taxable_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  total_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  total_amount_base NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  conversion_contract_id UUID,
  conversion_contract_issued_at TIMESTAMP,
  conversion_contract_hash VARCHAR(64),
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  created_by UUID NOT NULL,
  updated_by UUID NOT NULL,
  CONSTRAINT uq_quotation_tenant_company_num_rev UNIQUE (tenant_id, company_id, quotation_number, revision_number),
  CONSTRAINT chk_sales_quotation_status CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'REVISED', 'CANCELLED', 'CONVERTED'))
);

CREATE INDEX IF NOT EXISTS idx_quotation_customer ON sales_quotations (tenant_id, company_id, customer_id);
CREATE INDEX IF NOT EXISTS idx_quotation_status ON sales_quotations (tenant_id, company_id, status);
CREATE INDEX IF NOT EXISTS idx_quotation_date ON sales_quotations (tenant_id, company_id, quotation_date);

CREATE TABLE IF NOT EXISTS sales_quotation_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quotation_id UUID NOT NULL REFERENCES sales_quotations(id) ON DELETE CASCADE,
  tenant_id VARCHAR(64) NOT NULL,
  company_id UUID NOT NULL,
  line_number INTEGER NOT NULL,
  product_id UUID NOT NULL REFERENCES products(id),
  product_code_snapshot VARCHAR(64) NOT NULL,
  product_name_snapshot VARCHAR(255) NOT NULL,
  description TEXT,
  uom VARCHAR(32) NOT NULL REFERENCES uom_definitions(code),
  quantity NUMERIC(18,4) NOT NULL,
  unit_price NUMERIC(18,4) NOT NULL,
  discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  allocated_header_discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  gross_amount NUMERIC(15,2) NOT NULL,
  taxable_amount NUMERIC(15,2) NOT NULL,
  hsn_sac VARCHAR(16) NOT NULL,
  cgst_rate NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  cgst_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  sgst_rate NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  sgst_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  igst_rate NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  igst_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
  line_total NUMERIC(15,2) NOT NULL,
  pricing_source VARCHAR(64) NOT NULL,
  pricing_rule_id UUID REFERENCES pricing_rules(id),
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_quotation_line_num UNIQUE (quotation_id, line_number)
);
