-- Migration: 015_phase3_5_sales_returns_credit_notes.sql
-- Description: Create sales_returns, sales_return_lines, sales_credit_notes, and sales_credit_note_lines tables

CREATE TABLE IF NOT EXISTS sales_returns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id VARCHAR(64) NOT NULL,
  company_id UUID NOT NULL REFERENCES companies(id),
  return_number VARCHAR(64) NOT NULL,
  customer_id UUID NOT NULL REFERENCES customers(id),
  original_sales_invoice_id UUID NOT NULL REFERENCES sales_invoices(id),
  original_sales_delivery_id UUID REFERENCES sales_deliveries(id),
  return_date VARCHAR(10) NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  notes TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by UUID NOT NULL,
  updated_by UUID NOT NULL,
  approved_by UUID REFERENCES users(id),
  approved_at TIMESTAMP,
  cancelled_by UUID REFERENCES users(id),
  cancelled_at TIMESTAMP,
  cancellation_reason TEXT,
  CONSTRAINT uq_sales_return_tenant_company_num UNIQUE (tenant_id, company_id, return_number),
  CONSTRAINT chk_sales_return_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'CREDIT_NOTE_CREATED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_sales_return_customer ON sales_returns(tenant_id, company_id, customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_return_invoice ON sales_returns(tenant_id, company_id, original_sales_invoice_id);
CREATE INDEX IF NOT EXISTS idx_sales_return_status ON sales_returns(tenant_id, company_id, status);
CREATE INDEX IF NOT EXISTS idx_sales_return_date ON sales_returns(tenant_id, company_id, return_date);

CREATE TABLE IF NOT EXISTS sales_return_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  return_id UUID NOT NULL REFERENCES sales_returns(id) ON DELETE CASCADE,
  original_invoice_line_id UUID NOT NULL REFERENCES sales_invoice_lines(id),
  original_delivery_line_id UUID REFERENCES sales_delivery_lines(id),
  tenant_id VARCHAR(64) NOT NULL,
  company_id UUID NOT NULL,
  line_number INTEGER NOT NULL,
  product_id UUID NOT NULL REFERENCES products(id),
  product_code_snapshot VARCHAR(64) NOT NULL,
  product_name_snapshot VARCHAR(255) NOT NULL,
  description TEXT,
  uom VARCHAR(32) NOT NULL,
  original_invoiced_quantity NUMERIC(18, 4) NOT NULL,
  previously_returned_quantity NUMERIC(18, 4) NOT NULL DEFAULT 0.0000,
  return_quantity NUMERIC(18, 4) NOT NULL,
  unit_price NUMERIC(18, 4) NOT NULL,
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  gross_amount NUMERIC(15, 2) NOT NULL,
  taxable_amount NUMERIC(15, 2) NOT NULL,
  hsn_sac VARCHAR(16) NOT NULL,
  cgst_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  cgst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  sgst_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  sgst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  igst_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  igst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  tax_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  line_total NUMERIC(15, 2) NOT NULL,
  reason TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_sales_return_line_num UNIQUE (return_id, line_number),
  CONSTRAINT chk_sales_return_line_qty_pos CHECK (return_quantity > 0)
);

CREATE TABLE IF NOT EXISTS sales_credit_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id VARCHAR(64) NOT NULL,
  company_id UUID NOT NULL REFERENCES companies(id),
  credit_note_number VARCHAR(64) NOT NULL,
  sales_return_id UUID REFERENCES sales_returns(id),
  original_sales_invoice_id UUID NOT NULL REFERENCES sales_invoices(id),
  original_invoice_number_snapshot VARCHAR(64) NOT NULL,
  customer_id UUID NOT NULL REFERENCES customers(id),
  credit_note_date VARCHAR(10) NOT NULL,
  billing_address_snapshot JSONB NOT NULL,
  shipping_address_snapshot JSONB NOT NULL,
  contact_snapshot JSONB,
  reason TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  subtotal_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  taxable_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  cgst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  sgst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  igst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  tax_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  total_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  ar_document_id UUID REFERENCES ar_documents(id),
  ar_allocation_id UUID REFERENCES ar_allocations(id),
  journal_entry_id UUID REFERENCES journal_entries(id),
  posted_at TIMESTAMP,
  posted_by UUID REFERENCES users(id),
  notes TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by UUID NOT NULL,
  updated_by UUID NOT NULL,
  cancelled_by UUID REFERENCES users(id),
  cancelled_at TIMESTAMP,
  cancellation_reason TEXT,
  CONSTRAINT uq_sales_credit_note_tenant_company_num UNIQUE (tenant_id, company_id, credit_note_number),
  CONSTRAINT chk_sales_credit_note_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'POSTED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_sales_credit_note_customer ON sales_credit_notes(tenant_id, company_id, customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_credit_note_invoice ON sales_credit_notes(tenant_id, company_id, original_sales_invoice_id);
CREATE INDEX IF NOT EXISTS idx_sales_credit_note_return ON sales_credit_notes(tenant_id, company_id, sales_return_id);
CREATE INDEX IF NOT EXISTS idx_sales_credit_note_status ON sales_credit_notes(tenant_id, company_id, status);

CREATE TABLE IF NOT EXISTS sales_credit_note_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  credit_note_id UUID NOT NULL REFERENCES sales_credit_notes(id) ON DELETE CASCADE,
  sales_return_line_id UUID REFERENCES sales_return_lines(id),
  original_invoice_line_id UUID NOT NULL REFERENCES sales_invoice_lines(id),
  tenant_id VARCHAR(64) NOT NULL,
  company_id UUID NOT NULL,
  line_number INTEGER NOT NULL,
  product_id UUID NOT NULL REFERENCES products(id),
  product_code_snapshot VARCHAR(64) NOT NULL,
  product_name_snapshot VARCHAR(255) NOT NULL,
  description TEXT,
  uom VARCHAR(32) NOT NULL,
  returned_quantity NUMERIC(18, 4) NOT NULL,
  unit_price NUMERIC(18, 4) NOT NULL,
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  gross_amount NUMERIC(15, 2) NOT NULL,
  taxable_amount NUMERIC(15, 2) NOT NULL,
  hsn_sac VARCHAR(16) NOT NULL,
  cgst_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  cgst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  sgst_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  sgst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  igst_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  igst_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  tax_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  line_total NUMERIC(15, 2) NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_sales_credit_note_line_num UNIQUE (credit_note_id, line_number),
  CONSTRAINT chk_sales_credit_note_line_qty_pos CHECK (returned_quantity > 0)
);
