import { pgTable, uuid, varchar, numeric, integer, text, timestamp, uniqueIndex, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './platform.js';
import { companies, suppliers, products } from './master.js';
import { purchaseOrders, purchaseOrderLines } from './sourcing-purchase-order.js';
import { goodsReceipts, goodsReceiptLines } from './goods-receipt.js';
import { supplierBills, supplierBillLines } from './supplier-bill.js';
import { apDocuments } from './accounts-payable.js';
import { journalEntries } from './accounting.js';

export const procurementReturns = pgTable('procurement_returns', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull().references(() => companies.id),
  branchId: uuid('branch_id'),
  returnNumber: varchar('return_number', { length: 64 }).notNull(),
  supplierId: uuid('supplier_id').notNull().references(() => suppliers.id),
  purchaseOrderId: uuid('purchase_order_id').references(() => purchaseOrders.id),
  goodsReceiptId: uuid('goods_receipt_id').references(() => goodsReceipts.id),
  originalSupplierBillId: uuid('original_supplier_bill_id').references(() => supplierBills.id),
  returnDate: varchar('return_date', { length: 10 }).notNull(),
  reason: text('reason').notNull(),
  status: varchar('status', { length: 32 }).notNull().default('DRAFT'),
  notes: text('notes'),
  currency: varchar('currency', { length: 3 }).notNull().default('INR'),
  subtotalAmount: numeric('subtotal_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  cgstAmount: numeric('cgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  sgstAmount: numeric('sgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  igstAmount: numeric('igst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  utgstAmount: numeric('utgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  cessAmount: numeric('cess_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  totalAmount: numeric('total_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  debitNoteId: uuid('debit_note_id'),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by').notNull(),
  approvedBy: uuid('approved_by').references(() => users.id),
  approvedAt: timestamp('approved_at'),
  cancelledBy: uuid('cancelled_by').references(() => users.id),
  cancelledAt: timestamp('cancelled_at'),
  cancellationReason: text('cancellation_reason'),
}, (table) => ({
  tenantCompanyReturnNumIdx: uniqueIndex('uq_procurement_return_tenant_company_num').on(table.tenantId, table.companyId, table.returnNumber),
  supplierIdx: index('idx_procurement_return_supplier').on(table.tenantId, table.companyId, table.supplierId),
  poIdx: index('idx_procurement_return_po').on(table.tenantId, table.companyId, table.purchaseOrderId),
  grnIdx: index('idx_procurement_return_grn').on(table.tenantId, table.companyId, table.goodsReceiptId),
  statusIdx: index('idx_procurement_return_status').on(table.tenantId, table.companyId, table.status),
  statusCheck: check('chk_procurement_return_status', sql`${table.status} IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'COMPLETED', 'CANCELLED')`),
}));

export const procurementReturnLines = pgTable('procurement_return_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  returnId: uuid('return_id').notNull().references(() => procurementReturns.id, { onDelete: 'cascade' }),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull(),
  lineNumber: integer('line_number').notNull(),
  purchaseOrderLineId: uuid('purchase_order_line_id').references(() => purchaseOrderLines.id),
  goodsReceiptLineId: uuid('goods_receipt_line_id').references(() => goodsReceiptLines.id),
  supplierBillLineId: uuid('supplier_bill_line_id').references(() => supplierBillLines.id),
  productId: uuid('product_id').references(() => products.id),
  productCodeSnapshot: varchar('product_code_snapshot', { length: 64 }),
  productNameSnapshot: varchar('product_name_snapshot', { length: 255 }),
  description: text('description').notNull(),
  uom: varchar('uom', { length: 32 }).notNull(),
  acceptedQuantity: numeric('accepted_quantity', { precision: 18, scale: 4 }).notNull().default('0.0000'),
  previouslyReturnedQuantity: numeric('previously_returned_quantity', { precision: 18, scale: 4 }).notNull().default('0.0000'),
  returnedQuantity: numeric('returned_quantity', { precision: 18, scale: 4 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 18, scale: 4 }).notNull(),
  discountPercent: numeric('discount_percent', { precision: 5, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  grossAmount: numeric('gross_amount', { precision: 15, scale: 2 }).notNull(),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull(),
  hsnSac: varchar('hsn_sac', { length: 16 }),
  cgstRate: numeric('cgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  cgstAmount: numeric('cgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  sgstRate: numeric('sgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  sgstAmount: numeric('sgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  igstRate: numeric('igst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  igstAmount: numeric('igst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  utgstAmount: numeric('utgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  cessAmount: numeric('cess_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  lineTotal: numeric('line_total', { precision: 15, scale: 2 }).notNull(),
  expenseAccountId: varchar('expense_account_id', { length: 64 }),
  reason: text('reason'),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  returnLineNumIdx: uniqueIndex('uq_procurement_return_line_num').on(table.returnId, table.lineNumber),
  qtyPosCheck: check('chk_procurement_return_line_qty_pos', sql`${table.returnedQuantity} > 0`),
}));

export const supplierDebitNotes = pgTable('supplier_debit_notes', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull().references(() => companies.id),
  branchId: uuid('branch_id'),
  debitNoteNumber: varchar('debit_note_number', { length: 64 }).notNull(),
  procurementReturnId: uuid('procurement_return_id').references(() => procurementReturns.id),
  originalSupplierBillId: uuid('original_supplier_bill_id').references(() => supplierBills.id),
  originalInvoiceNumberSnapshot: varchar('original_invoice_number_snapshot', { length: 64 }),
  supplierId: uuid('supplier_id').notNull().references(() => suppliers.id),
  debitNoteDate: varchar('debit_note_date', { length: 10 }).notNull(),
  reason: text('reason').notNull(),
  status: varchar('status', { length: 32 }).notNull().default('DRAFT'),
  subtotalAmount: numeric('subtotal_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  cgstAmount: numeric('cgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  sgstAmount: numeric('sgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  igstAmount: numeric('igst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  utgstAmount: numeric('utgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  cessAmount: numeric('cess_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  totalAmount: numeric('total_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  apDocumentId: uuid('ap_document_id').references(() => apDocuments.id),
  journalEntryId: uuid('journal_entry_id').references(() => journalEntries.id),
  postedAt: timestamp('posted_at'),
  postedBy: uuid('posted_by').references(() => users.id),
  notes: text('notes'),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by').notNull(),
  cancelledBy: uuid('cancelled_by').references(() => users.id),
  cancelledAt: timestamp('cancelled_at'),
  cancellationReason: text('cancellation_reason'),
}, (table) => ({
  tenantCompanyDebitNoteNumIdx: uniqueIndex('uq_supplier_debit_note_tenant_company_num').on(table.tenantId, table.companyId, table.debitNoteNumber),
  supplierIdx: index('idx_supplier_debit_note_supplier').on(table.tenantId, table.companyId, table.supplierId),
  billIdx: index('idx_supplier_debit_note_bill').on(table.tenantId, table.companyId, table.originalSupplierBillId),
  returnIdx: index('idx_supplier_debit_note_return').on(table.tenantId, table.companyId, table.procurementReturnId),
  statusIdx: index('idx_supplier_debit_note_status').on(table.tenantId, table.companyId, table.status),
  statusCheck: check('chk_supplier_debit_note_status', sql`${table.status} IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'POSTED', 'CANCELLED')`),
}));

export const supplierDebitNoteLines = pgTable('supplier_debit_note_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  debitNoteId: uuid('debit_note_id').notNull().references(() => supplierDebitNotes.id, { onDelete: 'cascade' }),
  procurementReturnLineId: uuid('procurement_return_line_id').references(() => procurementReturnLines.id),
  goodsReceiptLineId: uuid('goods_receipt_line_id').references(() => goodsReceiptLines.id),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull(),
  lineNumber: integer('line_number').notNull(),
  productId: uuid('product_id').references(() => products.id),
  productCodeSnapshot: varchar('product_code_snapshot', { length: 64 }),
  productNameSnapshot: varchar('product_name_snapshot', { length: 255 }),
  description: text('description').notNull(),
  uom: varchar('uom', { length: 32 }).notNull(),
  returnedQuantity: numeric('returned_quantity', { precision: 18, scale: 4 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 18, scale: 4 }).notNull(),
  discountPercent: numeric('discount_percent', { precision: 5, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  grossAmount: numeric('gross_amount', { precision: 15, scale: 2 }).notNull(),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull(),
  hsnSac: varchar('hsn_sac', { length: 16 }),
  cgstRate: numeric('cgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  cgstAmount: numeric('cgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  sgstRate: numeric('sgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  sgstAmount: numeric('sgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  igstRate: numeric('igst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  igstAmount: numeric('igst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  utgstAmount: numeric('utgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  cessAmount: numeric('cess_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  lineTotal: numeric('line_total', { precision: 15, scale: 2 }).notNull(),
  expenseAccountId: varchar('expense_account_id', { length: 64 }),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  debitNoteLineNumIdx: uniqueIndex('uq_supplier_debit_note_line_num').on(table.debitNoteId, table.lineNumber),
  qtyPosCheck: check('chk_supplier_debit_note_line_qty_pos', sql`${table.returnedQuantity} > 0`),
}));

export type ProcurementReturn = typeof procurementReturns.$inferSelect;
export type NewProcurementReturn = typeof procurementReturns.$inferInsert;
export type ProcurementReturnLine = typeof procurementReturnLines.$inferSelect;
export type NewProcurementReturnLine = typeof procurementReturnLines.$inferInsert;
export type SupplierDebitNote = typeof supplierDebitNotes.$inferSelect;
export type NewSupplierDebitNote = typeof supplierDebitNotes.$inferInsert;
export type SupplierDebitNoteLine = typeof supplierDebitNoteLines.$inferSelect;
export type NewSupplierDebitNoteLine = typeof supplierDebitNoteLines.$inferInsert;
