import { pgTable, uuid, varchar, numeric, integer, text, jsonb, timestamp, uniqueIndex, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './platform.js';
import { companies } from './master.js';
import { customers, products, commercialAddresses, commercialContacts, pricingRules, uomDefinitions } from './commercial-master.js';
import { salesQuotations, salesQuotationLines } from './sales.js';

export const salesOrders = pgTable('sales_orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull().references(() => companies.id),
  orderNumber: varchar('order_number', { length: 64 }).notNull(),
  quotationId: uuid('quotation_id').notNull().references(() => salesQuotations.id),
  quotationNumber: varchar('quotation_number', { length: 64 }).notNull(),
  revisionNumber: integer('revision_number').notNull(),
  // Unique immutable application contract identifier (NOT a database FK - no contract DB table exists)
  conversionContractId: uuid('conversion_contract_id').notNull(),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  orderDate: varchar('order_date', { length: 10 }).notNull(),
  currency: varchar('currency', { length: 3 }).notNull().default('INR'),
  exchangeRate: numeric('exchange_rate', { precision: 18, scale: 6 }).notNull().default('1.000000'),
  salesRepresentativeId: uuid('sales_representative_id').references(() => users.id),
  billingAddressId: uuid('billing_address_id').notNull().references(() => commercialAddresses.id),
  shippingAddressId: uuid('shipping_address_id').notNull().references(() => commercialAddresses.id),
  billingAddressSnapshot: jsonb('billing_address_snapshot').notNull(),
  shippingAddressSnapshot: jsonb('shipping_address_snapshot').notNull(),
  contactId: uuid('contact_id').references(() => commercialContacts.id),
  contactSnapshot: jsonb('contact_snapshot'),
  status: varchar('status', { length: 32 }).notNull().default('DRAFT'),
  notes: text('notes'),
  termsAndConditions: text('terms_and_conditions'),
  subtotalAmount: numeric('subtotal_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  headerDiscountAmount: numeric('header_discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  totalAmount: numeric('total_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  totalAmountBase: numeric('total_amount_base', { precision: 15, scale: 2 }).notNull().default('0.00'),
  creditOverrideBy: uuid('credit_override_by').references(() => users.id),
  creditOverrideReason: text('credit_override_reason'),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by').notNull(),
}, (table) => ({
  tenantCompanyOrderNumIdx: uniqueIndex('uq_sales_order_tenant_company_num').on(table.tenantId, table.companyId, table.orderNumber),
  contractIdIdx: uniqueIndex('uq_sales_order_contract_id').on(table.tenantId, table.companyId, table.conversionContractId),
  customerIdx: index('idx_sales_order_customer').on(table.tenantId, table.companyId, table.customerId),
  statusIdx: index('idx_sales_order_status').on(table.tenantId, table.companyId, table.status),
  dateIdx: index('idx_sales_order_date').on(table.tenantId, table.companyId, table.orderDate),
  statusCheck: check('chk_sales_order_status', sql`${table.status} IN ('DRAFT', 'CONFIRMED', 'CANCELLED', 'COMPLETED')`),
}));

export const salesOrderLines = pgTable('sales_order_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').notNull().references(() => salesOrders.id, { onDelete: 'cascade' }),
  // Relational traceability: explicit DB FK to sales_quotation_lines.id with ON DELETE RESTRICT
  quotationLineId: uuid('quotation_line_id').notNull().references(() => salesQuotationLines.id, { onDelete: 'restrict' }),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull(),
  lineNumber: integer('line_number').notNull(),
  productId: uuid('product_id').notNull().references(() => products.id),
  productCodeSnapshot: varchar('product_code_snapshot', { length: 64 }).notNull(),
  productNameSnapshot: varchar('product_name_snapshot', { length: 255 }).notNull(),
  description: text('description'),
  uom: varchar('uom', { length: 32 }).notNull().references(() => uomDefinitions.code),
  orderedQuantity: numeric('ordered_quantity', { precision: 18, scale: 4 }).notNull(),
  deliveredQuantity: numeric('delivered_quantity', { precision: 18, scale: 4 }).notNull().default('0.0000'),
  invoicedQuantity: numeric('invoiced_quantity', { precision: 18, scale: 4 }).notNull().default('0.0000'),
  cancelledQuantity: numeric('cancelled_quantity', { precision: 18, scale: 4 }).notNull().default('0.0000'),
  unitPrice: numeric('unit_price', { precision: 18, scale: 4 }).notNull(),
  discountPercent: numeric('discount_percent', { precision: 5, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  allocatedHeaderDiscountAmount: numeric('allocated_header_discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  grossAmount: numeric('gross_amount', { precision: 15, scale: 2 }).notNull(),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull(),
  hsnSac: varchar('hsn_sac', { length: 16 }).notNull(),
  cgstRate: numeric('cgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  cgstAmount: numeric('cgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  sgstRate: numeric('sgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  sgstAmount: numeric('sgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  igstRate: numeric('igst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  igstAmount: numeric('igst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  lineTotal: numeric('line_total', { precision: 15, scale: 2 }).notNull(),
  pricingSource: varchar('pricing_source', { length: 64 }).notNull(),
  pricingRuleId: uuid('pricing_rule_id').references(() => pricingRules.id),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  orderLineNumIdx: uniqueIndex('uq_sales_order_line_num').on(table.orderId, table.lineNumber),
}));
