import { pgTable, uuid, varchar, numeric, integer, text, jsonb, timestamp, uniqueIndex, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './platform.js';
import { companies, branches } from './master.js';
import { customers, products, commercialAddresses, commercialContacts, uomDefinitions } from './commercial-master.js';
import { salesOrders, salesOrderLines } from './sales-order.js';

export const salesDeliveries = pgTable('sales_deliveries', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull().references(() => companies.id),
  branchId: uuid('branch_id').references(() => branches.id),
  deliveryNumber: varchar('delivery_number', { length: 64 }).notNull(),
  salesOrderId: uuid('sales_order_id').notNull().references(() => salesOrders.id, { onDelete: 'restrict' }),
  salesOrderNumber: varchar('sales_order_number', { length: 64 }).notNull(),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  deliveryDate: varchar('delivery_date', { length: 10 }).notNull(),
  shippingAddressId: uuid('shipping_address_id').notNull().references(() => commercialAddresses.id),
  shippingAddressSnapshot: jsonb('shipping_address_snapshot').notNull(),
  contactId: uuid('contact_id').references(() => commercialContacts.id),
  contactSnapshot: jsonb('contact_snapshot'),
  warehouseReference: varchar('warehouse_reference', { length: 128 }),
  transporterName: varchar('transporter_name', { length: 255 }),
  vehicleNumber: varchar('vehicle_number', { length: 64 }),
  lrNumber: varchar('lr_number', { length: 64 }),
  lrDate: varchar('lr_date', { length: 10 }),
  notes: text('notes'),
  status: varchar('status', { length: 32 }).notNull().default('DRAFT'),
  pickedAt: timestamp('picked_at'),
  pickedBy: uuid('picked_by').references(() => users.id),
  packedAt: timestamp('packed_at'),
  packedBy: uuid('packed_by').references(() => users.id),
  dispatchedAt: timestamp('dispatched_at'),
  dispatchedBy: uuid('dispatched_by').references(() => users.id),
  deliveredAt: timestamp('delivered_at'),
  deliveredBy: uuid('delivered_by').references(() => users.id),
  cancelledAt: timestamp('cancelled_at'),
  cancelledBy: uuid('cancelled_by').references(() => users.id),
  cancellationReason: text('cancellation_reason'),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by').notNull(),
}, (table) => ({
  tenantCompanyDeliveryNumIdx: uniqueIndex('uq_sales_delivery_tenant_company_num').on(table.tenantId, table.companyId, table.deliveryNumber),
  orderIdx: index('idx_sales_delivery_order').on(table.tenantId, table.companyId, table.salesOrderId),
  customerIdx: index('idx_sales_delivery_customer').on(table.tenantId, table.companyId, table.customerId),
  statusIdx: index('idx_sales_delivery_status').on(table.tenantId, table.companyId, table.status),
  dateIdx: index('idx_sales_delivery_date').on(table.tenantId, table.companyId, table.deliveryDate),
  statusCheck: check('chk_sales_delivery_status', sql`${table.status} IN ('DRAFT', 'PICKED', 'PACKED', 'DISPATCHED', 'DELIVERED', 'CANCELLED')`),
}));

export const salesDeliveryLines = pgTable('sales_delivery_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  deliveryId: uuid('delivery_id').notNull().references(() => salesDeliveries.id, { onDelete: 'cascade' }),
  salesOrderLineId: uuid('sales_order_line_id').notNull().references(() => salesOrderLines.id, { onDelete: 'restrict' }),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull(),
  lineNumber: integer('line_number').notNull(),
  productId: uuid('product_id').notNull().references(() => products.id),
  productCodeSnapshot: varchar('product_code_snapshot', { length: 64 }).notNull(),
  productNameSnapshot: varchar('product_name_snapshot', { length: 255 }).notNull(),
  description: text('description'),
  uom: varchar('uom', { length: 32 }).notNull().references(() => uomDefinitions.code),
  orderedQuantitySnapshot: numeric('ordered_quantity_snapshot', { precision: 18, scale: 4 }).notNull(),
  previouslyDeliveredQuantitySnapshot: numeric('previously_delivered_quantity_snapshot', { precision: 18, scale: 4 }).notNull().default('0.0000'),
  deliveryQuantity: numeric('delivery_quantity', { precision: 18, scale: 4 }).notNull(),
  rejectedQuantity: numeric('rejected_quantity', { precision: 18, scale: 4 }).notNull().default('0.0000'),
  remainingQuantitySnapshot: numeric('remaining_quantity_snapshot', { precision: 18, scale: 4 }).notNull(),
  notes: text('notes'),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  deliveryLineNumIdx: uniqueIndex('uq_sales_delivery_line_num').on(table.deliveryId, table.lineNumber),
  orderLineIdx: index('idx_sales_delivery_line_so_line').on(table.tenantId, table.companyId, table.salesOrderLineId),
  deliveryQtyPosCheck: check('chk_sales_delivery_line_qty_pos', sql`${table.deliveryQuantity} > 0`),
}));
