import { pgTable, uuid, varchar, numeric, integer, text, jsonb, timestamp, uniqueIndex, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './platform.js';
import { companies, branches } from './master.js';
import { customers, products, commercialAddresses, commercialContacts, uomDefinitions } from './commercial-master.js';
import { salesOrders, salesOrderLines } from './sales-order.js';
import { salesDeliveries, salesDeliveryLines } from './sales-delivery.js';

export const salesInvoices = pgTable('sales_invoices', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull().references(() => companies.id),
  branchId: uuid('branch_id').references(() => branches.id),
  invoiceNumber: varchar('invoice_number', { length: 64 }).notNull(),
  salesOrderId: uuid('sales_order_id').references(() => salesOrders.id, { onDelete: 'restrict' }),
  salesOrderNumber: varchar('sales_order_number', { length: 64 }),
  salesDeliveryId: uuid('sales_delivery_id').references(() => salesDeliveries.id, { onDelete: 'restrict' }),
  salesDeliveryNumber: varchar('sales_delivery_number', { length: 64 }),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  invoiceDate: varchar('invoice_date', { length: 10 }).notNull(),
  dueDate: varchar('due_date', { length: 10 }).notNull(),
  currency: varchar('currency', { length: 3 }).notNull().default('INR'),
  exchangeRate: numeric('exchange_rate', { precision: 18, scale: 6 }).notNull().default('1.000000'),
  billingAddressId: uuid('billing_address_id').notNull().references(() => commercialAddresses.id),
  billingAddressSnapshot: jsonb('billing_address_snapshot').notNull(),
  shippingAddressId: uuid('shipping_address_id').notNull().references(() => commercialAddresses.id),
  shippingAddressSnapshot: jsonb('shipping_address_snapshot').notNull(),
  contactId: uuid('contact_id').references(() => commercialContacts.id),
  contactSnapshot: jsonb('contact_snapshot'),
  status: varchar('status', { length: 32 }).notNull().default('DRAFT'),
  notes: text('notes'),
  termsAndConditions: text('terms_and_conditions'),
  subtotalAmount: numeric('subtotal_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  headerDiscountAmount: numeric('header_discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  cgstAmount: numeric('cgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  sgstAmount: numeric('sgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  igstAmount: numeric('igst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  totalAmount: numeric('total_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  totalAmountBase: numeric('total_amount_base', { precision: 15, scale: 2 }).notNull().default('0.00'),
  arDocumentId: varchar('ar_document_id', { length: 64 }),
  arOpenItemId: varchar('ar_open_item_id', { length: 64 }),
  journalEntryId: varchar('journal_entry_id', { length: 64 }),
  postedAt: timestamp('posted_at'),
  postedBy: uuid('posted_by').references(() => users.id),
  cancelledAt: timestamp('cancelled_at'),
  cancelledBy: uuid('cancelled_by').references(() => users.id),
  cancellationReason: text('cancellation_reason'),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by').notNull(),
}, (table) => ({
  tenantCompanyNumIdx: uniqueIndex('uq_sales_invoice_tenant_company_num').on(table.tenantId, table.companyId, table.invoiceNumber),
  orderIdx: index('idx_sales_invoice_order').on(table.tenantId, table.companyId, table.salesOrderId),
  customerIdx: index('idx_sales_invoice_customer').on(table.tenantId, table.companyId, table.customerId),
  statusIdx: index('idx_sales_invoice_status').on(table.tenantId, table.companyId, table.status),
  dateIdx: index('idx_sales_invoice_date').on(table.tenantId, table.companyId, table.invoiceDate),
  statusCheck: check('chk_sales_invoice_status', sql`${table.status} IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'POSTED', 'PARTIALLY_SETTLED', 'SETTLED', 'CANCELLED', 'REVERSED')`),
}));

export const salesInvoiceLines = pgTable('sales_invoice_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  invoiceId: uuid('invoice_id').notNull().references(() => salesInvoices.id, { onDelete: 'cascade' }),
  salesOrderLineId: uuid('sales_order_line_id').references(() => salesOrderLines.id, { onDelete: 'restrict' }),
  salesDeliveryLineId: uuid('sales_delivery_line_id').references(() => salesDeliveryLines.id, { onDelete: 'restrict' }),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull(),
  lineNumber: integer('line_number').notNull(),
  productId: uuid('product_id').notNull().references(() => products.id),
  productCodeSnapshot: varchar('product_code_snapshot', { length: 64 }).notNull(),
  productNameSnapshot: varchar('product_name_snapshot', { length: 255 }).notNull(),
  description: text('description'),
  uom: varchar('uom', { length: 32 }).notNull().references(() => uomDefinitions.code),
  invoicedQuantity: numeric('invoiced_quantity', { precision: 18, scale: 4 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 18, scale: 4 }).notNull(),
  discountPercent: numeric('discount_percent', { precision: 5, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  allocatedHeaderDiscountAmount: numeric('allocated_header_discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  grossAmount: numeric('gross_amount', { precision: 15, scale: 2 }).notNull(),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull(),
  hsnSac: varchar('hsn_sac', { length: 16 }).notNull(),
  cgstRate: numeric('cgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  cgstAmount: numeric('cgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  sgstRate: numeric('sgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  sgstAmount: numeric('sgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  igstRate: numeric('igst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  igstAmount: numeric('igst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  lineTotal: numeric('line_total', { precision: 15, scale: 2 }).notNull(),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  invoiceLineNumIdx: uniqueIndex('uq_sales_invoice_line_num').on(table.invoiceId, table.lineNumber),
  orderLineIdx: index('idx_sales_invoice_line_so_line').on(table.tenantId, table.companyId, table.salesOrderLineId),
  invoiceQtyPosCheck: check('chk_sales_invoice_line_qty_pos', sql`${table.invoicedQuantity} > 0`),
}));
