import { pgTable, uuid, varchar, numeric, integer, text, jsonb, timestamp, uniqueIndex, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './platform.js';
import { companies } from './master.js';
import { customers, products, commercialAddresses, commercialContacts, pricingLists, pricingRules, uomDefinitions } from './commercial-master.js';

export const salesQuotations = pgTable('sales_quotations', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull().references(() => companies.id),
  quotationNumber: varchar('quotation_number', { length: 64 }).notNull(),
  revisionNumber: integer('revision_number').notNull().default(1),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  quotationDate: varchar('quotation_date', { length: 10 }).notNull(),
  validityDate: varchar('validity_date', { length: 10 }).notNull(),
  currency: varchar('currency', { length: 3 }).notNull().default('INR'),
  exchangeRate: numeric('exchange_rate', { precision: 18, scale: 6 }).notNull().default('1.000000'),
  salesRepresentativeId: uuid('sales_representative_id').references(() => users.id),
  pricingListId: uuid('pricing_list_id').references(() => pricingLists.id),
  billingAddressId: uuid('billing_address_id').notNull().references(() => commercialAddresses.id),
  shippingAddressId: uuid('shipping_address_id').notNull().references(() => commercialAddresses.id),
  billingAddressSnapshot: jsonb('billing_address_snapshot').notNull(),
  shippingAddressSnapshot: jsonb('shipping_address_snapshot').notNull(),
  contactId: uuid('contact_id').references(() => commercialContacts.id),
  contactSnapshot: jsonb('contact_snapshot'),
  status: varchar('status', { length: 32 }).notNull().default('DRAFT'),
  notes: text('notes'),
  termsAndConditions: text('terms_and_conditions'),
  subtotalAmount: numeric('subtotal_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  headerDiscountAmount: numeric('header_discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  totalAmount: numeric('total_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  totalAmountBase: numeric('total_amount_base', { precision: 15, scale: 2 }).notNull().default('0.00'),
  conversionContractId: uuid('conversion_contract_id'),
  conversionContractIssuedAt: timestamp('conversion_contract_issued_at'),
  conversionContractHash: varchar('conversion_contract_hash', { length: 64 }),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by').notNull(),
  updatedBy: uuid('updated_by').notNull(),
}, (table) => ({
  tenantCompanyNumberRevIdx: uniqueIndex('uq_quotation_tenant_company_num_rev').on(table.tenantId, table.companyId, table.quotationNumber, table.revisionNumber),
  customerIdx: index('idx_quotation_customer').on(table.tenantId, table.companyId, table.customerId),
  statusIdx: index('idx_quotation_status').on(table.tenantId, table.companyId, table.status),
  dateIdx: index('idx_quotation_date').on(table.tenantId, table.companyId, table.quotationDate),
  statusCheck: check('chk_sales_quotation_status', sql`${table.status} IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'REVISED', 'CANCELLED', 'CONVERTED')`),
}));

export const salesQuotationLines = pgTable('sales_quotation_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  quotationId: uuid('quotation_id').notNull().references(() => salesQuotations.id, { onDelete: 'cascade' }),
  tenantId: varchar('tenant_id', { length: 64 }).notNull(),
  companyId: uuid('company_id').notNull(),
  lineNumber: integer('line_number').notNull(),
  productId: uuid('product_id').notNull().references(() => products.id),
  productCodeSnapshot: varchar('product_code_snapshot', { length: 64 }).notNull(),
  productNameSnapshot: varchar('product_name_snapshot', { length: 255 }).notNull(),
  description: text('description'),
  uom: varchar('uom', { length: 32 }).notNull().references(() => uomDefinitions.code),
  quantity: numeric('quantity', { precision: 18, scale: 4 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 18, scale: 4 }).notNull(),
  discountPercent: numeric('discount_percent', { precision: 5, scale: 2 }).notNull().default('0.00'),
  discountAmount: numeric('discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  allocatedHeaderDiscountAmount: numeric('allocated_header_discount_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  grossAmount: numeric('gross_amount', { precision: 15, scale: 2 }).notNull(),
  taxableAmount: numeric('taxable_amount', { precision: 15, scale: 2 }).notNull(),
  hsnSac: varchar('hsn_sac', { length: 16 }).notNull(),
  cgstRate: numeric('cgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  cgstAmount: numeric('cgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  sgstRate: numeric('sgst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  sgstAmount: numeric('sgst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  igstRate: numeric('igst_rate', { precision: 5, scale: 2 }).notNull().default('0.00'),
  igstAmount: numeric('igst_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  taxAmount: numeric('tax_amount', { precision: 15, scale: 2 }).notNull().default('0.00'),
  lineTotal: numeric('line_total', { precision: 15, scale: 2 }).notNull(),
  pricingSource: varchar('pricing_source', { length: 64 }).notNull(),
  pricingRuleId: uuid('pricing_rule_id').references(() => pricingRules.id),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  quotationLineIdx: uniqueIndex('uq_quotation_line_num').on(table.quotationId, table.lineNumber),
}));
